### ISSUE TITLE
MapperExtension import error

### ISSUE THREAD

**Issue by wilbertom** [zzzeek/sqlsoup#1]
When using `SQLAlchemy==1.4.17`. 

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wil/.virtualenvs/pwm-kpi-exporter-3/lib/python3.9/site-packages/sqlsoup.py", line 11, in <module>
    from sqlalchemy.orm.interfaces import MapperExtension, EXT_CONTINUE
ImportError: cannot import name 'MapperExtension' from 'sqlalchemy.orm.interfaces' 
```

`MapperExtension` was removed: https://github.com/sqlalchemy/sqlalchemy/commit/08757f05e027ead82a24cd8b7d4a3e90c5b01b59

**Comment by pabs3** [comment]
It was suggested in the Debian bug about this to switch from SQLSoup to the SQLAlchemy automap extension, since SQLSoup is no longer maintained.

https://bugs.debian.org/995781
https://docs.sqlalchemy.org/en/14/orm/extensions/automap.html
